package io.github.golangsupport.ide.inspections.unused

import com.intellij.codeInspection.LocalInspectionTool
import io.github.golangsupport.ide.GoSemanticIdeTestBase

/** The unused-declaration inspections in a light project (the files are not under `internal/` there: exported names stay quiet). */
class GoUnusedDeclarationInspectionsTest : GoSemanticIdeTestBase() {

    private val all: Array<LocalInspectionTool>
        get() = arrayOf(
            GoUnusedFunctionInspection(), GoUnusedExportedFunctionInspection(), GoUnusedTypeInspection(), GoUnusedExportedTypeInspection(),
            GoUnusedConstInspection(), GoUnusedGlobalVariableInspection(),
        )

    private fun doHighlight(name: String, text: String) {
        myFixture.enableInspections(*all)
        myFixture.configureByText(name, text.trimIndent())
        myFixture.checkHighlighting(true, false, true)
    }

    fun testUnexportedDeclarations() = doHighlight(
        "u7a.go",
        """
        package u7a

        func <warning descr="Unused function 'helper'">helper</warning>() { helper() }

        func used() int { return answer + level }

        type <warning descr="Unused type 'node'">node</warning> struct{ next *node }

        func (n *node) walk() *node { return n.next }

        type kept struct{}

        const (
            answer = 42
            <warning descr="Unused constant 'spare'">spare</warning> = 1
        )

        var <warning descr="Unused global variable 'cache'">cache</warning> = map[string]int{}

        var level = 1

        var _ = used

        func local() kept {
            const <warning descr="Unused constant 'limit'">limit</warning> = 3
            type <warning descr="Unused type 'pair'">pair</warning> struct{}
            return kept{}
        }

        // Exported names of a package other importers may use are not reported.
        func Exported() { _ = local }

        type Shown struct{}

        const Max = 1

        var Global = 2
        """,
    )

    fun testNotReported() = doHighlight(
        "u7b.go",
        """
        package u7b

        func init() {}

        //export callback
        func callback() {}

        func asm(x int) int

        func _() {}

        type iface interface{ M() }

        type impl struct{}

        func (impl) M() {}

        func (impl) unusedMethod() {}

        var _ iface = impl{}
        """,
    )

    fun testMainPackageExported() = doHighlight(
        "main.go",
        """
        package main

        func main() { _ = Used{} }

        type Used struct{}

        type <warning descr="Unused type 'Config'">Config</warning> struct{}

        func <warning descr="Unused function 'Helper'">Helper</warning>() {}
        """,
    )

    fun testTestEntryPointsAreNotReported() = doHighlight(
        "u7c_test.go",
        """
        package u7c

        import "testing"

        func TestA(t *testing.T) {}

        func BenchmarkA(b *testing.B) {}

        func ExampleA() {}

        func FuzzA(f *testing.F) {}

        func <warning descr="Unused function 'setup'">setup</warning>() {}
        """,
    )

    fun testGeneratedFileIsSkipped() = doHighlight(
        "u7d.go",
        """
        // Code generated by stringer; DO NOT EDIT.

        package u7d

        func unused() {}
        """,
    )

    fun testSafeDeleteFix() {
        myFixture.enableInspections(GoUnusedFunctionInspection())
        myFixture.configureByText("u7e.go", "package u7e\n\nfunc keep() {}\n\nfunc <caret>dead() {}\n\nvar _ = keep\n")
        myFixture.launchAction(myFixture.findSingleIntention("Safe delete"))
        myFixture.checkResult("package u7e\n\nfunc keep() {}\n\nvar _ = keep\n")
    }
}
