"""Generates the standard-library tables of the native lint rules (go-psi-ide, package ide.rules.builtin.vet).

    uv run tools/lint-rules/stdlib_data.py since [GOROOT]
        -> go-psi-ide/src/main/resources/lint/stdlib-since.txt: symbols added to the standard library in Go 1.22 or later, read from
           GOROOT/api/go1*.txt the way x/tools/internal/stdlib (generate.go) reads them: the first release that lists a symbol wins,
           interface methods are `(T).M`, concrete methods `(*T).M` / `(T).M`, fields `T.F`. Used by govet:stdversion; the analyzer only
           runs for modules at go1.21 or later, and file versions are never below go1.21, so older symbols are never "too new".
    uv run tools/lint-rules/stdlib_data.py deprecations [STATICCHECK_DIR]
        -> go-psi-ide/src/main/resources/lint/stdlib-deprecations.txt: staticcheck's knowledge.StdlibDeprecations (knowledge/deprecated.go,
           MIT, see NOTICE.md): name, deprecated since, alternative available since (`never` / `no longer`). Used by SA1019.

Rerun after a toolchain / staticcheck update and review the diff.
"""

import os
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
OUT = ROOT / "go-psi-ide" / "src" / "main" / "resources" / "lint"
MIN_MINOR = 22

SYM = re.compile(r"^pkg (\S+).*?, (var|func|type|const|method \([^)]*\)) ([\w]+)(.*)")


def remove_type_param(s: str) -> str:
    i = s.find("[")
    if i < 0:
        return s
    j = s.rfind("]")
    return s[:i] + s[j + 1:]


def since(goroot: Path) -> None:
    api = goroot / "api"
    symbols: dict[tuple[str, str], tuple[int, str]] = {}
    minor = 0
    while True:
        name = "go1.txt" if minor == 0 else f"go1.{minor}.txt"
        path = api / name
        if not path.exists():
            break
        for line in path.read_text(encoding="utf-8").splitlines():
            if not line or line.startswith("#"):
                continue
            m = SYM.match(line)
            if not m:
                raise SystemExit(f"invalid input: {path}: {line}")
            pkg, kind, sym, rest = m.groups()
            if kind.startswith("method "):
                recv = remove_type_param(kind[len("method "):])
                kind = "method"
                sym = f"{recv}.{sym}"
            elif kind == "type" and rest.startswith(" interface, "):
                method = rest[len(" interface, "):]
                if method.startswith("unexported methods") or " //deprecated" in method:
                    continue
                if "(" not in method:
                    continue
                kind = "method"
                sym = f"({sym}).{method.split('(', 1)[0]}"
            elif kind == "type" and rest.startswith(" struct, "):
                field = rest[len(" struct, "):]
                fname, _, ftype = field.partition(" ")
                if fname == "embedded":
                    ftype = ftype.lstrip("*")
                    if "." in ftype:
                        ftype = ftype.split(".", 1)[1]
                    fname = remove_type_param(ftype)
                kind = "field"
                sym = f"{sym}.{fname}"
            key = (pkg, sym)
            if key not in symbols:
                symbols[key] = (minor, kind)
        minor += 1
    rows = sorted((v[0], k[0], v[1], k[1]) for k, v in symbols.items() if v[0] >= MIN_MINOR)
    OUT.mkdir(parents=True, exist_ok=True)
    with open(OUT / "stdlib-since.txt", "w", encoding="utf-8", newline="\n") as f:
        f.write(f"# Generated by tools/lint-rules/stdlib_data.py from {goroot.as_posix()}/api (go1.{minor - 1}); minor<TAB>package<TAB>kind<TAB>symbol\n")
        for r in rows:
            f.write("\t".join(str(x) for x in r) + "\n")
    print(f"{len(rows)} symbols")


ENTRY = re.compile(r'^\s*"([^"]+)":\s*\{"(go1(?:\.\d+)?)",\s*(?:"(go1(?:\.\d+)?)"|(DeprecatedNeverUse|DeprecatedUseNoLonger))\},')


def deprecations(staticcheck: Path) -> None:
    src = staticcheck / "knowledge" / "deprecated.go"
    rows = []
    for line in src.read_text(encoding="utf-8").splitlines():
        m = ENTRY.match(line)
        if not m:
            continue
        name, since_v, alt, special = m.groups()
        alt = alt or {"DeprecatedNeverUse": "never", "DeprecatedUseNoLonger": "no longer"}[special]
        rows.append((name, since_v, alt))
    OUT.mkdir(parents=True, exist_ok=True)
    with open(OUT / "stdlib-deprecations.txt", "w", encoding="utf-8", newline="\n") as f:
        f.write(f"# Generated by tools/lint-rules/stdlib_data.py from staticcheck {staticcheck.name} knowledge/deprecated.go (MIT); name<TAB>since<TAB>alternative\n")
        for r in rows:
            f.write("\t".join(r) + "\n")
    print(f"{len(rows)} deprecations")


def main() -> None:
    if len(sys.argv) < 2 or sys.argv[1] not in ("since", "deprecations"):
        raise SystemExit(__doc__)
    if sys.argv[1] == "since":
        since(Path(sys.argv[2]) if len(sys.argv) > 2 else Path(os.environ.get("GOROOT", r"C:\Program Files\Go")))
    else:
        default = Path.home() / "go" / "pkg" / "mod" / "honnef.co" / "go" / "tools@v0.8.1"
        deprecations(Path(sys.argv[2]) if len(sys.argv) > 2 else default)


if __name__ == "__main__":
    main()
