package io.github.golangsupport.ide.rules.builtin.vet

/**
 * The standard-library tables of the batch-B6 checks, generated by `tools/lint-rules/stdlib_data.py` into `resources/lint/`:
 * symbols added in Go 1.22 and later (govet `stdversion`, from GOROOT/api) and staticcheck's stdlib deprecation knowledge (SA1019).
 */
internal object GoStdlibTables {

    /** A symbol of `stdlib-since.txt`: `Name`, `T.Field`, `(*T).Method`, `(T).Method`. */
    class Symbol(val minor: Int, val kind: String, val name: String) {
        val version: String get() = "go1.$minor"
    }

    /** package path -> symbol name -> symbol. */
    val since: Map<String, Map<String, Symbol>> by lazy {
        val out = HashMap<String, HashMap<String, Symbol>>()
        for (line in lines("/lint/stdlib-since.txt")) {
            val p = line.split('\t')
            if (p.size != 4) continue
            out.getOrPut(p[1]) { HashMap() }[p[3]] = Symbol(p[0].toInt(), p[2], p[3])
        }
        out
    }

    /** The simple names of [since] (the last segment of every symbol): a reference with another name is never too new. */
    val sinceNames: Set<String> by lazy { since.values.flatMap { m -> m.keys.map { it.substringAfterLast('.') } }.toSet() }

    /** A deprecation of staticcheck's table: since `go1.N`; the alternative available since `go1.M`, [NEVER_USE] or [NO_LONGER]. */
    class Deprecation(val since: String, val alternative: String)

    const val NEVER_USE = "never"
    const val NO_LONGER = "no longer"

    /** `path.Name`, `(path.T).Field`, `(*path.T).Method` -> deprecation. */
    val deprecations: Map<String, Deprecation> by lazy {
        lines("/lint/stdlib-deprecations.txt").mapNotNull { line ->
            val p = line.split('\t')
            if (p.size == 3) p[0] to Deprecation(p[1], p[2]) else null
        }.toMap()
    }

    private fun lines(resource: String): List<String> {
        val stream = GoStdlibTables::class.java.getResourceAsStream(resource) ?: return emptyList()
        return stream.bufferedReader(Charsets.UTF_8).use { r -> r.readLines().filter { it.isNotEmpty() && !it.startsWith("#") } }
    }
}
