package io.github.golangsupport

import com.intellij.codeInspection.ProblemHighlightType
import com.intellij.lang.annotation.HighlightSeverity
import io.github.golangsupport.ci.GoInspectFiles
import io.github.golangsupport.ci.GoInspectOptions
import io.github.golangsupport.ci.GoInspectRun
import io.github.golangsupport.ci.GoSarifLevel
import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertNull
import org.junit.Assert.assertTrue
import org.junit.Assert.fail
import org.junit.Rule
import org.junit.Test
import org.junit.rules.TemporaryFolder
import java.nio.file.Files
import java.nio.file.Path

class GoInspectOptionsTest {

    @get:Rule
    val temp = TemporaryFolder()

    @Test
    fun positionalArgumentsAndDefaults() {
        val o = GoInspectOptions.parse(listOf("go-inspect", "proj", "out/report.sarif"))
        assertEquals(Path.of("proj").toAbsolutePath().normalize(), o.projectDir)
        assertEquals(Path.of("out/report.sarif").toAbsolutePath().normalize(), o.output)
        assertNull(o.inspections)
        assertEquals(GoSarifLevel.NOTE, o.minLevel)
    }

    @Test
    fun optionsInBothSpellings() {
        val a = GoInspectOptions.parse(listOf("--inspections", "GoUnusedVariable, GoTypeMismatch", "p", "o.sarif", "--min-severity", "warning"))
        assertEquals(setOf("GoUnusedVariable", "GoTypeMismatch"), a.inspections)
        assertEquals(GoSarifLevel.WARNING, a.minLevel)
        val b = GoInspectOptions.parse(listOf("p", "o.sarif", "--min-severity=error", "--inspections=GoModVersions"))
        assertEquals(setOf("GoModVersions"), b.inspections)
        assertEquals(GoSarifLevel.ERROR, b.minLevel)
    }

    @Test
    fun badArgumentsAreUsageErrors() {
        for (args in listOf(listOf("p"), listOf("p", "o", "extra"), listOf("p", "o", "--min-severity", "fatal"), listOf("p", "o", "--inspections"),
            listOf("p", "o", "--inspections", " , "), listOf("p", "o", "--format", "json"))) {
            try {
                GoInspectOptions.parse(args)
                fail("accepted $args")
            } catch (_: GoInspectOptions.UsageException) {
            }
        }
    }

    @Test
    fun severityOfAProblem() {
        assertEquals(GoSarifLevel.ERROR, GoSarifLevel.of(ProblemHighlightType.GENERIC_ERROR_OR_WARNING, HighlightSeverity.ERROR))
        assertEquals(GoSarifLevel.WARNING, GoSarifLevel.of(ProblemHighlightType.LIKE_UNUSED_SYMBOL, HighlightSeverity.WARNING))
        assertEquals(GoSarifLevel.NOTE, GoSarifLevel.of(ProblemHighlightType.GENERIC_ERROR_OR_WARNING, HighlightSeverity.WEAK_WARNING))
        // an explicit type of the problem wins over the profile
        assertEquals(GoSarifLevel.ERROR, GoSarifLevel.of(ProblemHighlightType.GENERIC_ERROR, HighlightSeverity.WEAK_WARNING))
        assertEquals(GoSarifLevel.NOTE, GoSarifLevel.of(ProblemHighlightType.WEAK_WARNING, HighlightSeverity.ERROR))
        // fix-only problems and information level are not findings
        assertNull(GoSarifLevel.of(ProblemHighlightType.INFORMATION, HighlightSeverity.ERROR))
        assertNull(GoSarifLevel.of(ProblemHighlightType.GENERIC_ERROR_OR_WARNING, HighlightSeverity.INFORMATION))
        assertEquals(GoSarifLevel.NOTE, GoSarifLevel.ofOption("weak"))
    }

    @Test
    fun generatedCodeIsRecognisedBeforeThePackageClause() {
        assertTrue(GoInspectFiles.isGenerated("// Code generated by protoc-gen-go. DO NOT EDIT.\r\n\npackage pb\n"))
        assertTrue(GoInspectFiles.isGenerated("//go:build linux\n\n// Code generated by stringer; DO NOT EDIT.\n\npackage x\n"))
        assertFalse(GoInspectFiles.isGenerated("package x\n\n// Code generated by hand. DO NOT EDIT.\n"))
        assertFalse(GoInspectFiles.isGenerated("// Code generated by x. Edit freely.\npackage x\n"))
    }

    @Test
    fun walkSkipsWhatGoSkips() {
        val root = temp.root.toPath()
        for (rel in listOf("go.mod", "main.go", "main_test.go", "README.md", "pkg/a b.go", "vendor/x/x.go", "testdata/t.go", ".git/h.go", "_old/o.go", "sub/go.work", "sub/data.txt")) {
            Files.createDirectories(root.resolve(rel).parent)
            Files.writeString(root.resolve(rel), "package x\n")
        }
        val found = GoInspectRun.candidates(root).map { GoInspectFiles.relativeUri(root, it) }
        assertEquals(listOf("go.mod", "main.go", "main_test.go", "pkg/a%20b.go", "sub/go.work"), found)
    }
}
