package io.github.golangsupport

import com.google.gson.JsonParser
import com.intellij.codeInspection.ex.InspectionProfileImpl
import com.intellij.openapi.actionSystem.ActionManager
import com.intellij.openapi.actionSystem.ActionPlaces
import com.intellij.openapi.actionSystem.ActionUiKind
import com.intellij.openapi.actionSystem.AnAction
import com.intellij.openapi.actionSystem.AnActionEvent
import com.intellij.openapi.actionSystem.CommonDataKeys
import com.intellij.openapi.actionSystem.impl.SimpleDataContext
import com.intellij.openapi.application.ApplicationManager
import com.intellij.openapi.progress.EmptyProgressIndicator
import com.intellij.openapi.vfs.VfsUtilCore
import com.intellij.openapi.vfs.VirtualFile
import com.intellij.profile.codeInspection.InspectionProjectProfileManager
import com.intellij.testFramework.PlatformTestUtil
import com.intellij.testFramework.fixtures.BasePlatformTestCase
import io.github.golangsupport.ci.GoBatchInspections
import io.github.golangsupport.ci.GoExportSarifAction
import io.github.golangsupport.ci.GoInspectProfiles
import io.github.golangsupport.ci.GoInspectRun
import io.github.golangsupport.ci.GoInspectScope
import io.github.golangsupport.ide.inspections.GoUnusedVariableInspection
import io.github.golangsupport.mod.GoModVersionsInspection
import io.github.golangsupport.settings.GoFeatureSource
import io.github.golangsupport.settings.GoSettings
import java.nio.file.Files
import java.util.concurrent.Callable

/** The run behind Go | Export Inspections to SARIF and `go-inspect`, the scope and profile of Go | Inspect Project, and when the actions show. */
class GoInspectRunTest : BasePlatformTestCase() {
    private val settings get() = GoSettings.getInstance()
    private var server = true
    private var source = GoFeatureSource.GOPLS

    override fun setUp() {
        super.setUp()
        server = settings.languageServerEnabled
        source = settings.languageFeaturesSource
        // the editor's diagnostics come from gopls: the run must still get the native ones
        settings.languageServerEnabled = true
        settings.languageFeaturesSource = GoFeatureSource.GOPLS
        myFixture.enableInspections(GoUnusedVariableInspection(), GoModVersionsInspection())
    }

    override fun tearDown() {
        try {
            settings.languageServerEnabled = server
            settings.languageFeaturesSource = source
        } finally {
            super.tearDown()
        }
    }

    private val unused = "\n\nfunc f() {\n\tx := 1\n}\n"

    private fun fixture(): VirtualFile {
        myFixture.addFileToProject("ir/go.mod", "module ir\n\ngo 1.x\n")
        myFixture.addFileToProject("ir/main.go", "package ir$unused")
        myFixture.addFileToProject("ir/pkg/a b.go", "package pkg\n\nfunc g() {}\n")
        myFixture.addFileToProject("ir/gen.go", "// Code generated by stringer; DO NOT EDIT.\n\npackage ir\n\nfunc h() {\n\ty := 1\n}\n")
        myFixture.addFileToProject("ir/vendor/v/v.go", "package v$unused")
        myFixture.addFileToProject("ir/testdata/t.go", "package t$unused")
        myFixture.addFileToProject("ir/_old/o.go", "package o$unused")
        myFixture.addFileToProject("ir/README.md", "x")
        return myFixture.findFileInTempDir("ir")
    }

    private fun run(root: VirtualFile): GoInspectRun.Report {
        // the run is for a background thread: its non-blocking read actions must not run on the EDT
        val future = ApplicationManager.getApplication().executeOnPooledThread(Callable { GoInspectRun(project, root).run(EmptyProgressIndicator()) })
        return PlatformTestUtil.waitForFuture(future, 60_000)
    }

    fun testTheWalkSkipsWhatGoSkips() {
        val root = fixture()
        val found = com.intellij.openapi.application.ReadAction.compute<List<String?>, Throwable> { GoInspectRun.candidates(root).map { VfsUtilCore.getRelativePath(it, root, '/') } }
        assertEquals(listOf("gen.go", "go.mod", "main.go", "pkg/a b.go"), found)
    }

    fun testFindsTheProblemsAndSkipsVendorAndGeneratedCode() {
        val report = run(fixture())
        assertEquals(listOf("GoModVersions", "GoUnusedVariable"), report.tools.map { it.shortName })
        assertEquals(emptyList<String>(), report.notifications)
        // gen.go is read by the walk but left out as generated: three files inspected
        assertEquals(3, report.files)
        assertEquals(listOf("go.mod:GoModVersions", "main.go:GoUnusedVariable"), report.results.map { "${it.uri}:${it.ruleId}" }.sorted())
        assertEquals(4, report.results.single { it.ruleId == "GoUnusedVariable" }.region.startLine)
        assertEquals(1, report.exitCode)
        assertFalse("the gate is closed after the run", GoBatchInspections.isActive(project))
    }

    fun testTheReportIsSarif() {
        val report = run(fixture())
        val out = Files.createTempFile("go-inspect", ".sarif")
        try {
            Files.writeString(out, report.sarif("file:///C:/work/ir/"))
            val root = JsonParser.parseString(Files.readString(out)).asJsonObject
            assertEquals("2.1.0", root["version"].asString)
            val run = root.getAsJsonArray("runs")[0].asJsonObject
            val rules = run.getAsJsonObject("tool").getAsJsonObject("driver").getAsJsonArray("rules").map { it.asJsonObject["id"].asString }
            assertEquals(listOf("GoModVersions", "GoUnusedVariable"), rules)
            val results = run.getAsJsonArray("results").map { it.asJsonObject }
            assertEquals(listOf("go.mod", "main.go"), results.map { it.getAsJsonArray("locations")[0].asJsonObject.getAsJsonObject("physicalLocation").getAsJsonObject("artifactLocation")["uri"].asString })
            assertEquals("file:///C:/work/ir/", run.getAsJsonObject("originalUriBaseIds").getAsJsonObject("%SRCROOT%")["uri"].asString)
        } finally {
            Files.deleteIfExists(out)
        }
        assertEquals("1 finding", GoExportSarifAction.findings(1))
        assertEquals("92 findings", GoExportSarifAction.findings(92))
    }

    fun testTheScopeOfInspectProjectIsTheFilesOfGoInspect() {
        val root = fixture()
        val scope = GoInspectScope.of(project, null)
        fun has(path: String) = scope.contains(root.findFileByRelativePath(path)!!)
        assertTrue(has("main.go") && has("go.mod") && has("pkg/a b.go"))
        assertFalse(has("gen.go") || has("vendor/v/v.go") || has("testdata/t.go") || has("_old/o.go") || has("README.md"))
        val pkg = GoInspectScope.of(project, root.findChild("pkg"))
        assertTrue(pkg.contains(root.findFileByRelativePath("pkg/a b.go")!!))
        assertFalse(pkg.contains(root.findChild("main.go")!!))
        assertEquals("Go files in pkg", pkg.displayName)
    }

    fun testTheProfileOfInspectProjectHasOnlyTheGoTools() {
        val base = InspectionProjectProfileManager.getInstance(project).currentProfile
        val tools = GoInspectRun.tools(project, base, null)
        // light tests do not initialise the tools of a new profile unless asked; the IDE always does
        val init = InspectionProfileImpl.INIT_INSPECTIONS
        InspectionProfileImpl.INIT_INSPECTIONS = true
        val limited = try { GoInspectProfiles.limited(project, base, tools) } finally { InspectionProfileImpl.INIT_INSPECTIONS = init }
        assertEquals(tools.map { it.shortName }, limited.getAllEnabledInspectionTools(project).map { it.shortName }.sorted())
    }

    private fun update(id: String, file: VirtualFile?, contextMenu: Boolean): AnActionEvent {
        val action: AnAction = ActionManager.getInstance().getAction(id)
        val data = SimpleDataContext.builder().add(CommonDataKeys.PROJECT, project).apply { if (file != null) add(CommonDataKeys.VIRTUAL_FILE, file) }.build()
        val event = if (contextMenu) AnActionEvent.createEvent(data, action.templatePresentation.clone(), ActionPlaces.PROJECT_VIEW_POPUP, ActionUiKind.POPUP, null)
        else AnActionEvent.createEvent(data, action.templatePresentation.clone(), ActionPlaces.MAIN_MENU, ActionUiKind.MAIN_MENU, null)
        action.update(event)
        return event
    }

    fun testTheActionsShowForAGoProjectAndADirectory() {
        val root = fixture()
        for (id in listOf("Go.InspectProject", "Go.ExportSarif")) {
            assertTrue(id, update(id, null, contextMenu = false).presentation.isEnabled)
            val onDir = update(id, root.findChild("pkg"), contextMenu = true).presentation
            assertTrue(id, onDir.isEnabledAndVisible)
            val onFile = update(id, root.findChild("main.go"), contextMenu = true).presentation
            assertFalse(id, onFile.isVisible)
        }
    }
}
