package io.github.golangsupport

import com.intellij.analysis.problemsView.ProblemsCollector
import com.intellij.openapi.application.ApplicationManager
import com.intellij.openapi.application.ReadAction
import com.intellij.openapi.command.WriteCommandAction
import com.intellij.openapi.fileEditor.FileDocumentManager
import com.intellij.openapi.vfs.VfsUtilCore
import com.intellij.openapi.vfs.VirtualFile
import com.intellij.psi.PsiDocumentManager
import com.intellij.testFramework.PlatformTestUtil
import com.intellij.testFramework.fixtures.BasePlatformTestCase
import io.github.golangsupport.ci.GoBatchInspections
import io.github.golangsupport.ide.inspections.GoUnresolvedReferenceInspection
import io.github.golangsupport.ide.inspections.GoUnusedVariableInspection
import io.github.golangsupport.problems.GoProblemsScope
import io.github.golangsupport.problems.GoProjectProblems
import io.github.golangsupport.settings.GoFeatureSource
import io.github.golangsupport.settings.GoSettings
import java.util.concurrent.Callable

/** The background analysis of the project: the files it reads, a full pass, a change and its dependents, a deletion, the switch. */
class GoProjectProblemsTest : BasePlatformTestCase() {
    private val settings get() = GoSettings.getInstance()
    private var server = true
    private var source = GoFeatureSource.GOPLS
    private var analysis = true
    private var warnings = true
    private val service get() = GoProjectProblems.getInstance(project)

    override fun setUp() {
        super.setUp()
        server = settings.languageServerEnabled
        source = settings.languageFeaturesSource
        analysis = settings.projectAnalysis
        warnings = settings.projectAnalysisWarnings
        // the editor's diagnostics come from gopls: the background pass must still get the native ones, without opening the gate for the editor
        settings.languageServerEnabled = true
        settings.languageFeaturesSource = GoFeatureSource.GOPLS
        settings.projectAnalysis = true
        settings.projectAnalysisWarnings = true
        myFixture.enableInspections(GoUnusedVariableInspection(), GoUnresolvedReferenceInspection())
    }

    override fun tearDown() {
        try {
            service.clearForTests()
            settings.languageServerEnabled = server
            settings.languageFeaturesSource = source
            settings.projectAnalysis = analysis
            settings.projectAnalysisWarnings = warnings
        } finally {
            super.tearDown()
        }
    }

    private fun unused(name: String) = "\n\nfunc $name() {\n\t$name$name := 1\n}\n"

    private fun fixture(): VirtualFile {
        myFixture.addFileToProject("pp/go.mod", "module pp\n\ngo 1.22\n")
        myFixture.addFileToProject("pp/lib/lib.go", "package lib\n\nfunc F() int { return 1 }${unused("h")}")
        myFixture.addFileToProject("pp/lib/use.go", "package lib\n\nfunc use() int {\n\treturn F()\n}\n")
        myFixture.addFileToProject("pp/lib/gen.go", "// Code generated by stringer; DO NOT EDIT.\n\npackage lib${unused("k")}")
        myFixture.addFileToProject("pp/app/app.go", "package app\n\nimport \"pp/lib\"\n\nfunc g() int {\n\tx := 1\n\treturn lib.F()\n}\n")
        myFixture.addFileToProject("pp/other/o.go", "package other${unused("o")}")
        myFixture.addFileToProject("pp/vendor/v/v.go", "package v${unused("v")}")
        myFixture.addFileToProject("pp/lib/testdata/t.go", "package t${unused("t")}")
        myFixture.addFileToProject("pp/frontend/node_modules/m/m.go", "package m${unused("m")}")
        myFixture.addFileToProject("pp/frontend/app.js", "console.log(1)\n")
        myFixture.addFileToProject("pp/tools/go.mod", "module pp/tools\n\ngo 1.22\n")
        myFixture.addFileToProject("pp/tools/gen/main.go", "package main${unused("n")}")
        return myFixture.findFileInTempDir("pp")
    }

    private fun drain(): List<String> {
        val root = myFixture.findFileInTempDir("pp")
        val future = ApplicationManager.getApplication().executeOnPooledThread(Callable { service.drainForTests() })
        return PlatformTestUtil.waitForFuture(future, 60_000).map { VfsUtilCore.getRelativePath(it, root, '/') ?: it.path }
    }

    /** "file:line: inspection" of what the tab shows, sorted. */
    private fun shown(): List<String> {
        val root = myFixture.findFileInTempDir("pp")
        return service.shownProblems().flatMap { (file, problems) ->
            problems.map { "${VfsUtilCore.getRelativePath(file, root, '/')}:${it.line + 1}: ${it.finding.inspection}" }
        }.sorted()
    }

    private fun full(): List<String> {
        service.requestFull()
        return drain()
    }

    private fun edit(path: String, from: String, to: String) {
        val file = myFixture.findFileInTempDir(path)
        WriteCommandAction.runWriteCommandAction(project) {
            val document = FileDocumentManager.getInstance().getDocument(file)!!
            val at = document.text.indexOf(from)
            assertTrue(from, at >= 0)
            document.replaceString(at, at + from.length, to)
            PsiDocumentManager.getInstance(project).commitDocument(document)
        }
    }

    fun testTheFilesOfTheProject() {
        val root = fixture()
        val files = ReadAction.compute<List<String?>, Throwable> { GoProblemsScope.files(project).filter { VfsUtilCore.isAncestor(root, it, true) }.map { VfsUtilCore.getRelativePath(it, root, '/') } }
        // vendor, testdata and node_modules are left out; a nested module is in; the generated file is read and dropped by its marker
        assertEquals(listOf("app/app.go", "go.mod", "lib/gen.go", "lib/lib.go", "lib/use.go", "other/o.go", "tools/gen/main.go", "tools/go.mod"), files)
    }

    fun testTheDependentsOfAPackage() {
        val root = fixture()
        val lib = root.findFileByRelativePath("lib")!!
        val dependents = ReadAction.compute<List<String?>, Throwable> {
            GoProblemsScope.dependents(project, lib, except = lib.findChild("lib.go")).map { VfsUtilCore.getRelativePath(it, root, '/') }
        }
        assertEquals(listOf("app/app.go", "lib/gen.go", "lib/use.go"), dependents)
    }

    fun testAFullPassCollectsTheProblemsOfTheProject() {
        fixture()
        full()
        assertEquals(listOf("app/app.go:6: GoUnusedVariable", "lib/lib.go:6: GoUnusedVariable", "other/o.go:4: GoUnusedVariable", "tools/gen/main.go:4: GoUnusedVariable"), shown())
        assertFalse("the gate of the editor stays closed", GoBatchInspections.isActive(project))
        // the rows are in the Project Errors tab
        val app = myFixture.findFileInTempDir("pp/app/app.go")
        assertEquals(1, ProblemsCollector.getInstance(project).getFileProblemCount(app))
        assertTrue(ProblemsCollector.getInstance(project).getFileProblems(app).single().text.endsWith("(Unused variable)"))
    }

    fun testAChangeAnalysesTheFileAndItsDependentsOnly() {
        fixture()
        full()
        // a declaration changes: the package and its importers again, nothing else
        edit("pp/lib/lib.go", "func F()", "func G()")
        val analysed = drain()
        assertEquals(listOf("lib/lib.go", "app/app.go", "lib/gen.go", "lib/use.go"), analysed)
        assertTrue(shown().toString(), "lib/use.go:4: GoUnresolvedReference" in shown())
        // a body changes: the file alone
        edit("pp/lib/lib.go", "hh := 1", "hh := 2")
        assertEquals(listOf("lib/lib.go"), drain())
        // the declaration back: the error in the other file of the package goes
        edit("pp/lib/lib.go", "func G()", "func F()")
        drain()
        assertFalse(shown().toString(), shown().any { "GoUnresolvedReference" in it })
    }

    fun testADeletedFileLeavesTheTab() {
        fixture()
        full()
        val app = myFixture.findFileInTempDir("pp/app/app.go")
        WriteCommandAction.runWriteCommandAction(project) { app.delete(this) }
        assertFalse(shown().toString(), shown().any { it.startsWith("app/") })
        assertEquals(0, ProblemsCollector.getInstance(project).getFileProblemCount(app))
    }

    fun testADeletedPackageAnalysesItsImporters() {
        fixture()
        full()
        val lib = myFixture.findFileInTempDir("pp/lib")
        WriteCommandAction.runWriteCommandAction(project) { lib.delete(this) }
        assertFalse(shown().toString(), shown().any { it.startsWith("lib/") })
        assertEquals(listOf("app/app.go"), drain())
    }

    fun testErrorsOnlyAndOff() {
        fixture()
        full()
        edit("pp/lib/lib.go", "func F()", "func G()")
        drain()
        settings.projectAnalysisWarnings = false
        service.settingsChanged()
        assertEquals(listOf("lib/use.go:4: GoUnresolvedReference"), shown())
        settings.projectAnalysis = false
        service.settingsChanged()
        assertEquals(emptyList<String>(), shown())
        assertEquals(emptyList<String>(), full())
        assertEquals(emptyList<String>(), shown())
    }
}
