## changed at Tue Sep 22 17:02:53 MSK 2026
#Tue Sep 22 17:02:53 MSK 2026
com.gigaide.database.elements.view.SqlFileFrameElement.shouldUse=true
com.gigaide.database.elements.view.SqlFileFrameExplorerElement.shouldUse=true
com.gigaide.database.elements.view.SqlStatementExplorerElement.shouldUse=true
com.gigaide.database.ui.treeview.DataSourcesViewNode.shouldUse=true
com.gigaide.elements.ext.marker.framework.java.JavaAnnotationRoled.shouldMark=true
com.gigaide.elements.ext.marker.framework.java.JavaCallRoled.shouldMark=true
com.gigaide.elements.ext.marker.framework.kt.KtAnnotationRoled.shouldMark=true
com.gigaide.elements.ext.marker.framework.kt.KtCallRoled.shouldMark=true
com.gigaide.elements.ext.marker.framework.kt.KtImplInheritRoled.shouldMark=true
com.gigaide.elements.ext.marker.solution.java.JavaClassSolution.shouldMark=true
com.gigaide.elements.ext.marker.solution.java.JavaVariableBeanUsage.shouldMark=true
com.gigaide.elements.ext.marker.solution.kt.KtClassSolution.shouldMark=true
com.gigaide.elements.ext.marker.solution.kt.KtVariableBeanUsage.shouldMark=true
com.gigaide.elements.ext.marker.tms.TmsLinkMethod.shouldMark=true
com.gigaide.elements.ext.menu.TmsToExplorerMarkerAction.shouldAct=true
com.gigaide.elements.ext.menu.ToFrameworkAction.shouldAct=true
com.gigaide.elements.ext.view.DefaultFrameElement.shouldUse=true
com.gigaide.elements.ext.view.DefaultFrameMarker.shouldUse=true
com.gigaide.elements.ext.view.DefaultFramework.shouldUse=true
com.gigaide.elements.ext.view.DefaultJavaxPA.shouldUse=true
com.gigaide.elements.ext.view.DefaultSolution.shouldUse=true
com.gigaide.elements.ext.view.DefaultSolutionElement.shouldUse=true
com.gigaide.elements.ext.view.DefaultSolutionMarker.shouldUse=true
com.gigaide.elements.ext.view.ExplorerFrameElement.shouldUse=true
com.gigaide.elements.ext.view.ExplorerFrameMarker.shouldUse=true
com.gigaide.elements.ext.view.ExplorerSolutionElement.shouldUse=true
com.gigaide.elements.ext.view.ExplorerSolutionMarker.shouldUse=true
com.gigaide.elements.ext.view.bean.uat.ExplorerUATEJBBean.shouldUse=true
com.gigaide.elements.ext.view.bean.uat.ExplorerUATSpringBean.shouldUse=true
com.gigaide.elements.ext.view.bean.uat.java.DefaultJavaEJB.shouldUse=true
com.gigaide.elements.ext.view.bean.uat.java.DefaultJavaSpringAutowired.shouldUse=true
com.gigaide.elements.ext.view.bean.uat.kt.DefaultKtEJB.shouldUse=true
com.gigaide.elements.ext.view.bean.uat.kt.DefaultKtSpringAutowired.shouldUse=true
com.gigaide.elements.ext.view.bridge.uat.ExplorerUATSpringRepository.shouldUse=true
com.gigaide.elements.ext.view.bridge.uat.java.DefaultJavaSpringRepository.shouldUse=true
com.gigaide.elements.ext.view.bridge.uat.kt.DefaultKtSpringRepository.shouldUse=true
com.gigaide.elements.ext.view.data.DefaultJakartaPA.shouldUse=true
com.gigaide.elements.ext.view.data.uat.ExplorerUATJavaxPA.shouldUse=true
com.gigaide.elements.ext.view.data.uat.kt.DefaultKtJakartaPA.shouldUse=true
com.gigaide.elements.ext.view.data.uat.kt.DefaultKtJavaxPA.shouldUse=true
com.gigaide.elements.ext.view.endpoint.uat.ExplorerUATBlade.shouldUse=true
com.gigaide.elements.ext.view.endpoint.uat.ExplorerUATJaxRs.shouldUse=true
com.gigaide.elements.ext.view.endpoint.uat.ExplorerUATJaxWs.shouldUse=true
com.gigaide.elements.ext.view.endpoint.uat.ExplorerUATSpringController.shouldUse=true
com.gigaide.elements.ext.view.endpoint.uat.ExplorerUATSpringEndpoint.shouldUse=true
com.gigaide.elements.ext.view.endpoint.uat.java.DefaultJavaBlade.shouldUse=true
com.gigaide.elements.ext.view.endpoint.uat.java.DefaultJavaJakartaRs.shouldUse=true
com.gigaide.elements.ext.view.endpoint.uat.java.DefaultJavaJakartaWs.shouldUse=true
com.gigaide.elements.ext.view.endpoint.uat.java.DefaultJavaJaxRs.shouldUse=true
com.gigaide.elements.ext.view.endpoint.uat.java.DefaultJavaJaxWs.shouldUse=true
com.gigaide.elements.ext.view.endpoint.uat.java.DefaultJavaSpringController.shouldUse=true
com.gigaide.elements.ext.view.endpoint.uat.java.DefaultJavaSpringEndpoint.shouldUse=true
com.gigaide.elements.ext.view.endpoint.uat.kt.DefaultKtBlade.shouldUse=true
com.gigaide.elements.ext.view.endpoint.uat.kt.DefaultKtJakartaRs.shouldUse=true
com.gigaide.elements.ext.view.endpoint.uat.kt.DefaultKtJakartaWs.shouldUse=true
com.gigaide.elements.ext.view.endpoint.uat.kt.DefaultKtJaxRs.shouldUse=true
com.gigaide.elements.ext.view.endpoint.uat.kt.DefaultKtJaxWs.shouldUse=true
com.gigaide.elements.ext.view.endpoint.uat.kt.DefaultKtSpringController.shouldUse=true
com.gigaide.elements.ext.view.endpoint.uat.kt.DefaultKtSpringEndpoint.shouldUse=true
com.gigaide.elements.ext.view.factory.uat.ExplorerUATSpringFactory.shouldUse=true
com.gigaide.elements.ext.view.factory.uat.java.DefaultJavaSpringConfiguration.shouldUse=true
com.gigaide.elements.ext.view.factory.uat.kt.DefaultKtSpringConfiguration.shouldUse=true
com.gigaide.elements.ext.view.integration.uat.ExplorerUATSpringIntegration.shouldUse=true
com.gigaide.elements.ext.view.integration.uat.java.DefaultJavaSpringIntegration.shouldUse=true
com.gigaide.elements.ext.view.security.uat.ExplorerUATJakartaSecurity.shouldUse=true
com.gigaide.elements.ext.view.security.uat.ExplorerUATJavaxSecurity.shouldUse=true
com.gigaide.elements.ext.view.security.uat.ExplorerUATSpringSecurity.shouldUse=true
com.gigaide.elements.ext.view.security.uat.java.DefaultJavaJakartaSecurity.shouldUse=true
com.gigaide.elements.ext.view.security.uat.java.DefaultJavaJavaxSecurity.shouldUse=true
com.gigaide.elements.ext.view.security.uat.java.DefaultJavaSpringSecurity.shouldUse=true
com.gigaide.elements.ext.view.testing.uat.ExplorerUATAllureTesting.shouldUse=true
com.gigaide.elements.ext.view.testing.uat.java.DefaultJavaAllureTesting.shouldUse=true
com.gigaide.elements.ext.view.testing.uat.kt.DefaultKtAllureTesting.shouldUse=true
com.gigaide.elements.service.marker.config.MarkerConfigHolder.analyzePriority=false
com.gigaide.elements.service.marker.config.MarkerConfigHolder.autoAnalize=false
com.gigaide.endpoint.marker.environment.EnvironmentMarker.shouldMark=true
com.gigaide.endpoint.marker.interaction.EndpointMethodMarker.shouldMark=true
com.gigaide.endpoint.marker.interaction.InteractionHttpMethodMarker.shouldMark=true
com.gigaide.endpoint.marker.interaction.InteractionUrlMarker.shouldMark=true
com.gigaide.endpoint.menu.environment.SelectEnvironmentAction.shouldAct=true
com.gigaide.endpoint.menu.interection.EndpointToExplorerAction.shouldAct=true
com.gigaide.endpoint.menu.interection.InteractionRunAction.shouldAct=true
com.gigaide.endpoint.menu.interection.InteractionToExplorerAction.shouldAct=true
com.gigaide.endpoint.view.environment.EnvironmentSolutionElement.shouldUse=true
com.gigaide.endpoint.view.interaction.HttpMethodExplorerElement.shouldUse=true
com.gigaide.endpoint.view.interaction.InteractionExplorerFrameElement.shouldUse=true
com.gigaide.endpoint.view.interaction.InteractionExplorerSolutionElement.shouldUse=true
com.gigaide.endpoint.view.interaction.InteractionFileFrameElement.shouldUse=true
com.gigaide.endpoint.view.interaction.InteractionFileSolutionElement.shouldUse=true
com.gigaide.tms.view.TestCasesViewNode.shouldUse=true
com.gigaide.tms.view.TmsFolderViewNode.shouldUse=true
com.gigaide.tms.view.TmsTestCaseViewNode.shouldUse=true
com.gigaide.tms.view.TmsTestCasesViewNode.shouldUse=true
com.gigaide.tms.view.explorer.ExplorerTmsTestCaseViewNode.shouldUse=true
com.intellij.spring.elements.marker.NavigateToAutowiredCandidatesLineMarkerProvider.NavigateToAutowiredCandidatesLineMarkerElement.shouldMark=true
