import pytest

from gopsi_ml.corpus import gofiles


def test_generated_marker_before_package_clause():
    assert gofiles.is_generated("// Code generated by protoc-gen-go. DO NOT EDIT.\n\npackage x\n")
    assert gofiles.is_generated(
        "// Copyright\r\n// Code generated by stringer; DO NOT EDIT.\r\npackage x\r\n"
    )
    assert not gofiles.is_generated("package x\n\n// Code generated by hand. DO NOT EDIT.\n")
    assert not gofiles.is_generated("// Code generated, but edits welcome.\npackage x\n")


def test_uses_cgo():
    assert gofiles.uses_cgo('package x\n\nimport "C"\n')
    assert gofiles.uses_cgo('package x\n\nimport (\n\t"fmt"\n\t"C"\n)\n')
    assert not gofiles.uses_cgo('package x\n\nimport "fmt"\n')


@pytest.mark.parametrize(
    ("rel", "unit"),
    [
        ("net/http/server.go", "std/net"),
        ("cmd/compile/internal/ssa/x.go", "std/cmd/compile"),
        ("cmd/x.go", "std/cmd"),
        ("x.go", "std"),
    ],
)
def test_std_unit(rel, unit):
    assert gofiles.std_unit(rel) == unit


def test_split_is_stable_and_roughly_proportional():
    assert gofiles.split_of("golang.org/x/tools") == gofiles.split_of("golang.org/x/tools")
    counts: dict[str, int] = {}
    for i in range(10_000):
        s = gofiles.split_of(f"example.com/m{i}")
        counts[s] = counts.get(s, 0) + 1
    assert 7_600 < counts["train"] < 8_400
    assert 800 < counts["valid"] < 1_200
    assert 800 < counts["test"] < 1_200


@pytest.mark.parametrize("name", ["vendor", "testdata", ".git", "_examples"])
def test_excluded_dirs(name):
    assert gofiles.excluded_dir(name)
