import io
import zipfile

import pytest

from gopsi_ml.corpus import fetch, manifest, sources
from gopsi_ml.corpus.selection import Candidate, Locked

MODULE = "example.com/Foo"
VERSION = "v1.2.3"


def module_zip(files: dict[str, str]) -> bytes:
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w") as zf:
        for name, body in files.items():
            zf.writestr(f"{MODULE}@{VERSION}/{name}", body)
    return buf.getvalue()


@pytest.mark.parametrize(
    ("rel", "kept"),
    [
        ("a.go", True),
        ("pkg/b_test.go", True),
        ("go.mod", True),
        ("LICENSE", True),
        ("pkg/LICENSE", False),
        ("README.md", False),
        ("vendor/x/y.go", False),
        ("pkg/testdata/z.go", False),
        ("_examples/main.go", False),
        ("../evil.go", False),
    ],
)
def test_keep_member(rel, kept):
    assert fetch.keep_member(rel) is kept


def test_fetch_one_extracts_and_marks(tmp_path, monkeypatch):
    payload = module_zip(
        {
            "go.mod": f"module {MODULE}\n",
            "LICENSE": "Permission is hereby granted, free of charge, to any person",
            "foo.go": "package foo\n",
            "gen.go": "// Code generated by x. DO NOT EDIT.\n\npackage foo\n",
            "dup.go": "package foo\n",
            "testdata/bad.go": "not go",
            "README.md": "readme",
        }
    )
    requested = []

    def fake_download(url, to, max_bytes, timeout):
        requested.append(url)
        to.write_bytes(payload)
        return "sha"

    monkeypatch.setattr(fetch, "_download", fake_download)
    locked = Locked(Candidate(MODULE, VERSION, ("MIT",), 7, 0), "dependents")
    out = tmp_path / "modules"

    result = fetch.fetch_one(locked, out)
    assert result.status == "ok" and result.files == 5
    assert requested == ["https://proxy.golang.org/example.com/!foo/@v/v1.2.3.zip"]
    dest = out / "example.com" / "!foo@v1.2.3"
    assert (dest / fetch.MARKER).is_file()
    assert not (dest / "testdata").exists() and not (dest / "README.md").exists()
    assert fetch.fetch_one(locked, out).status == "cached"

    roots = list(sources.fetched_modules(out))
    assert [(r.module, r.version, r.allowed) for r in roots] == [(MODULE, VERSION, True)]

    table, stats = manifest.build(roots)
    rows = {r["rel_path"]: r for r in table.to_pylist()}
    assert set(rows) == {"foo.go", "gen.go", "dup.go"}
    assert rows["gen.go"]["is_generated"] and not rows["foo.go"]["is_generated"]
    # files are visited in name order, so dup.go is the original and foo.go the copy
    assert rows["dup.go"]["duplicate_of"] is None
    assert rows["foo.go"]["duplicate_of"] == rows["dup.go"]["path"]
    assert {r["split"] for r in rows.values()} == {rows["foo.go"]["split"]}
    assert stats.files == 3 and stats.duplicates == 1 and stats.generated == 1


def test_gomodcache_takes_highest_version_and_skips_nested_modules(tmp_path):
    mit = "Permission is hereby granted, free of charge, to any person"
    for version in ("v1.0.0", "v1.10.0", "v1.9.0"):
        root = tmp_path / "github.com" / "!some" / f"mod@{version}"
        (root / "sub").mkdir(parents=True)
        (root / "LICENSE").write_text(mit)
        (root / "a.go").write_text(f"package a // {version}\n")
        (root / "sub" / "go.mod").write_text("module github.com/Some/mod/sub\n")
        (root / "sub" / "b.go").write_text("package sub\n")
    (tmp_path / "cache" / "download").mkdir(parents=True)

    roots = list(sources.gomodcache_modules(tmp_path))
    assert [(r.module, r.version, r.license, r.allowed) for r in roots] == [
        ("github.com/Some/mod", "v1.10.0", "MIT", True)
    ]
    table, _ = manifest.build(roots)
    assert table.column("rel_path").to_pylist() == ["a.go"]


def test_module_order_prefers_goroot_then_fetched(tmp_path):
    a = tmp_path / "a"
    b = tmp_path / "b"
    for d in (a, b):
        d.mkdir()
        (d / "x.go").write_text(f"package x // {d.name}\n")
    roots = [
        sources.ModuleRoot("gomodcache", "example.com/m", "v1.0.0", a, "MIT", True),
        sources.ModuleRoot("fetched", "example.com/m", "v1.1.0", b, "MIT", True),
        sources.ModuleRoot("fetched", "example.com/gpl", "v1.0.0", b, "GPL-3.0-only", False),
    ]
    table, stats = manifest.build(roots)
    assert table.column("version").to_pylist() == ["v1.1.0"]
    assert (stats.modules_skipped_duplicate, stats.modules_skipped_license) == (1, 1)


def test_goroot_covers_std_and_cmd(tmp_path):
    src = tmp_path / "src"
    for rel in ("go.mod", "net/http/a.go", "cmd/go.mod", "cmd/compile/internal/b.go", "cmd/vendor/x/c.go"):
        (src / rel).parent.mkdir(parents=True, exist_ok=True)
        (src / rel).write_text("package x\n" if rel.endswith(".go") else "module x\n")
    (tmp_path / "VERSION").write_text("go1.27.1\ntime 2026\n")
    table, _ = manifest.build(sources.goroot_modules(tmp_path))
    got = sorted(zip(table.column("module").to_pylist(), table.column("unit").to_pylist(), strict=True))
    assert got == [("cmd", "std/cmd/compile"), ("std", "std/net")]
    assert set(table.column("version").to_pylist()) == {"go1.27.1"}
