package io.github.golangsupport.ide.inspections

import io.github.golangsupport.ide.GoSemanticIdeTestBase

/** The doc comment inspection (golint `exported`): missing and malformed comments, groups, skipped files, both quick fixes. */
class GoDocCommentInspectionTest : GoSemanticIdeTestBase() {

    private fun doHighlight(text: String, fileName: String = "a.go") {
        myFixture.enableInspections(GoDocCommentInspection())
        myFixture.configureByText(fileName, text.trimIndent() + "\n")
        myFixture.checkHighlighting(true, false, true)
    }

    private fun doFix(before: String, fix: String, after: String) {
        myFixture.enableInspections(GoDocCommentInspection())
        myFixture.configureByText("a.go", before.trimIndent() + "\n")
        val offered = myFixture.availableIntentions
        myFixture.launchAction(offered.singleOrNull { it.text == fix } ?: error("$fix not in ${offered.map { it.text }}"))
        myFixture.checkResult(after.trimIndent().replace("@@", "") + "\n")
    }

    fun testMissingOnFuncTypeMethodVarAndConst() = doHighlight(
        """
        package p

        func <weak_warning descr="exported function Foo should have comment or be unexported">Foo</weak_warning>() {}

        type <weak_warning descr="exported type Bar should have comment or be unexported">Bar</weak_warning> struct{}

        func (b *Bar) <weak_warning descr="exported method Bar.Run should have comment or be unexported">Run</weak_warning>() {}

        var <weak_warning descr="exported var V should have comment or be unexported">V</weak_warning> = 1

        const <weak_warning descr="exported const C should have comment or be unexported">C</weak_warning> = 2

        // Ok does things.
        func Ok() {}

        func unexported() {}

        type hidden struct{}

        func (h hidden) Exported() {}
        """
    )

    fun testGroupCommentCountsForAllSpecs() = doHighlight(
        """
        package p

        // Colors of the palette.
        const (
        	Red = iota
        	Green
        )

        const (
        	<weak_warning descr="exported const Blue should have comment (or a comment on this block) or be unexported">Blue</weak_warning> = iota
        	// Cyan is cold.
        	Cyan
        )

        var (
        	// Name is the name.
        	Name = "x"
        	<weak_warning descr="exported var Other should have comment (or a comment on this block) or be unexported">Other</weak_warning> = "y"
        )
        """
    )

    fun testWrongStart() = doHighlight(
        """
        package p

        <weak_warning descr="comment on exported function Foo should be of the form \"Foo ...\"">// Does things.</weak_warning>
        func Foo() {}

        <weak_warning descr="comment on exported type Bar should be of the form \"Bar ...\"">// bar is a thing.</weak_warning>
        type Bar struct{}

        <weak_warning descr="comment on exported method Bar.Run should be of the form \"Run ...\"">// Starts it.</weak_warning>
        func (b Bar) Run() {}

        <weak_warning descr="comment on exported var V should be of the form \"V ...\"">// Value of it.</weak_warning>
        var V = 1
        """
    )

    fun testArticlesAndDeprecatedAreAllowed() = doHighlight(
        """
        package p

        // A Foo is a thing.
        type Foo struct{}

        // An Item is an item.
        type Item struct{}

        // The Bar is the bar.
        func Bar() {}

        // Deprecated: use Bar.
        func Old() {}

        // Baz, with a comma.
        func Baz() {}

        /* Qux is block. */
        func Qux() {}
        """
    )

    fun testSkippedFiles() {
        doHighlight("package p\n\nfunc Foo() {}", "a_test.go")
        doHighlight("package main\n\nfunc Foo() {}", "main.go")
        doHighlight("// Code generated by tool. DO NOT EDIT.\n\npackage p\n\nfunc Foo() {}", "gen.go")
    }

    fun testAddDocCommentOnFunction() = doFix(
        """
        package p

        func Fo<caret>o() {}
        """,
        "Add doc comment",
        """
        package p

        // Foo @@
        func Foo() {}
        """,
    )

    fun testAddDocCommentInGroupKeepsIndent() = doFix(
        """
        package p

        var (
        	// A is a.
        	A = 1
        	B<caret> = 2
        )
        """,
        "Add doc comment",
        """
        package p

        var (
        	// A is a.
        	A = 1
        	// B @@
        	B = 2
        )
        """,
    )

    fun testAddDocCommentOnMethod() = doFix(
        """
        package p

        type T struct{}

        func (t T) Ru<caret>n() {}
        """,
        "Add doc comment",
        """
        package p

        type T struct{}

        // Run @@
        func (t T) Run() {}
        """,
    )

    fun testStartCommentRewritesFirstWord() = doFix(
        """
        package p

        // <caret>foo does things.
        func Foo() {}
        """,
        "Start comment with 'Foo'",
        """
        package p

        // Foo does things.
        func Foo() {}
        """,
    )

    fun testStartCommentPrependsName() = doFix(
        """
        package p

        // <caret>Returns the answer.
        func Answer() int { return 42 }
        """,
        "Start comment with 'Answer'",
        """
        package p

        // Answer returns the answer.
        func Answer() int { return 42 }
        """,
    )
}
