package io.github.golangsupport.lint.config

/**
 * What a golangci-lint configuration (`.golangci.yml|yaml|json`, formats 1 and 2) says, in a neutral form: the native rule engine adapts it
 * (linter enabled -> its rules on, settings -> rule options, exclusions -> suppression). Pure data, no platform; v1 keys are normalized to
 * the v2 shape (`linters-settings` -> [settings], `issues.exclude-rules` -> [exclusionRules], `enable-all`/`disable-all` -> [default]).
 */
data class GolangciConfig(
    /** 1 or 2: `version: "2"` at the top level, otherwise 1. */
    val version: Int,
    /** The base set before [enable]/[disable]: v2 `linters.default`; v1 `enable-all` -> ALL, `disable-all` -> NONE, otherwise STANDARD. */
    val default: GolangciDefault = GolangciDefault.STANDARD,
    /** v1 `linters.fast: true`: only the fast linters of the resulting set. */
    val fastOnly: Boolean = false,
    /** v1 `linters.presets` (`bugs`, `style`, …); v2 has none. */
    val presets: List<String> = emptyList(),
    val enable: List<String> = emptyList(),
    val disable: List<String> = emptyList(),
    /** Linter -> its settings as parsed (nested maps, lists, strings, numbers, booleans); keys as written (`exclude-functions`). */
    val settings: Map<String, Map<String, Any?>> = emptyMap(),
    /** v2 `formatters.enable`; v1 formatters are linters and stay in [enable]. */
    val formatters: List<String> = emptyList(),
    val formatterSettings: Map<String, Map<String, Any?>> = emptyMap(),
    /** Every rule that hides issues: v2 `linters.exclusions.rules` and presets, v1 `issues.exclude-rules`, `issues.exclude` and the default `EXC` patterns. */
    val exclusionRules: List<GolangciExclusionRule> = emptyList(),
    /** v2 `linters.exclusions.presets`; v1: the presets equivalent to `exclude-use-default` (informational, their rules are in [exclusionRules]). */
    val exclusionPresets: List<String> = emptyList(),
    /** Files never reported: v2 `exclusions.paths`; v1 `exclude-files`/`skip-files`. Matched against the slash-separated relative path. */
    val excludedPaths: List<Regex> = emptyList(),
    /** v2 `exclusions.paths-except`: a path matching one of these is kept even if [excludedPaths] matches. */
    val keptPaths: List<Regex> = emptyList(),
    /** v1 `exclude-dirs`/`skip-dirs` (plus the default dirs while `exclude-dirs-use-default`), matched against the directory of the file. */
    val excludedDirs: List<Regex> = emptyList(),
    val generated: GolangciGenerated = GolangciGenerated.LAX,
    val buildTags: List<String> = emptyList(),
    /** `run.tests`: false drops `_test.go` files. */
    val tests: Boolean = true,
    /** v1 `issues.exclude-case-sensitive`; text and source patterns are case-insensitive otherwise, as golangci compiles them. */
    val caseSensitive: Boolean = false,
    /** `severity.default` (v1 `default-severity`), as written (`error`, `warning`, `info`, `@linter`). */
    val defaultSeverity: String? = null,
    val severityRules: List<GolangciSeverityRule> = emptyList(),
    /** What was ignored or did not compile; the rest of the file is still used. */
    val warnings: List<String> = emptyList(),
) {
    fun settingsOf(linter: String): Map<String, Any?> = settings[linter].orEmpty()
}

enum class GolangciDefault { STANDARD, ALL, NONE, FAST }

/** `exclusions.generated` (v1 `exclude-generated`): LAX — any "code generated" / "do not edit" / "autogenerated file" comment; STRICT — the Go convention line only. */
enum class GolangciGenerated { LAX, STRICT, DISABLE }

/**
 * One exclusion rule: it hides an issue when every condition that is set holds (golangci's semantics). [linters] empty means every linter.
 * [preset] names where a built-in rule comes from (`std-error-handling`, `EXC0001`), null for the user's rules.
 */
data class GolangciExclusionRule(
    val path: Regex? = null,
    val pathExcept: Regex? = null,
    val text: Regex? = null,
    val source: Regex? = null,
    val linters: Set<String> = emptySet(),
    val preset: String? = null,
) {
    fun matches(relPath: String, linter: String, text: String, sourceLine: String?): Boolean =
        (linters.isEmpty() || linter in linters) &&
            (path == null || path.containsMatchIn(relPath)) &&
            (pathExcept == null || !pathExcept.containsMatchIn(relPath)) &&
            (this.text == null || this.text.containsMatchIn(text)) &&
            (source == null || (sourceLine != null && source.containsMatchIn(sourceLine)))
}

data class GolangciSeverityRule(val severity: String, val rule: GolangciExclusionRule)

/** The result of reading a configuration file: never an exception. */
sealed class GolangciConfigResult {
    abstract val file: String?

    data class Parsed(val config: GolangciConfig, override val file: String? = null) : GolangciConfigResult()

    /** A format without a bundled parser (TOML). */
    data class Unsupported(val reason: String, override val file: String? = null) : GolangciConfigResult()

    /** Malformed file: the message of the parser, golangci itself would refuse to run. */
    data class Failed(val message: String, override val file: String? = null) : GolangciConfigResult()

    val configOrNull: GolangciConfig? get() = (this as? Parsed)?.config
}
